Use /proc/mounts if /etc/mtab does not exist
cloudfoundry/gosigar pull request #60
Opened 2022-09-09 12:57 UTC by digiserg

2022-09-15 14:43 UTC, rkoster requested changes
@digiserg Thanks for you PR, could you also add a test for you changes?

2022-09-20 15:13 UTC, cunnie requested changes

2022-09-20 15:13 UTC, cunnie commented on sigar_linux.go
> +		source = "/proc/mounts"
shouldn't this be `src = "/proc/mounts"`?

2022-09-20 15:19 UTC, cunnie commented
> > @digiserg Thanks for you PR, could you also add a test for you changes?
> 
> I don't believe I can. The test would need something that deletes `/etc/mtab` beforehand. Having said that, you may decide to always use `/proc/mounts`. I can't think on any scenario where `/proc/mounts` is not available.

I think you might be able to find sample tests here: <https://github.com/cloudfoundry/gosigar/blob/39b9f29585a9a47e3cf0e370404e12a3272988af/sigar_linux_test.go#L16-L19>

I think you can run `bin/test-unit` to run the tests.

2022-09-21 15:45 UTC, digiserg commented
Added. With thanks to @rgooding for his help

2022-10-03 17:31 UTC, cunnie commented
Hey @digiserg, nice work. We're almost at the finish line. Could you please do the following:

- run `goimports` on the codebase. Not the `vendor` subdirectory, but everywhere else.
- Could you please squash the commits into a single commit? There's no reason for "Variable name typo" being in the git history if it doesn't need to be.
- Could you please describe what problem you're trying to fix. "Use /proc/mounts if /etc/mtab does not exist" describes _what_ change you made, but it's less important than _why_ you made the change. _Why_ you made the change is important.

For example, here's a made-up example of the type of commit I'm looking for:

```
`FileSystemList.Get()` works properly on Fedora

The sigar package expects the existence of `/etc/mtab`; however, on some distributions such as Fedora this file does not exist, and attempting to retrieve the filesystem usage results in a "ENOFILE file does not exist". This commit addresses that shortcoming by falling back to using `/proc/mounts/`
```

2022-10-05 15:03 UTC, cunnie commented
Hey @digiserg thanks for the changes. I appreciate your patience with this.

- Could you please squash the commits into a single commit? There's no reason for a separate unit test commit.
- Could you please modify the commit message to include the use case you're trying to fix? Where did you see this error? Was it in an Ubuntu Xenial distribution? Maybe an Alpine Linux Docker image? if coders need to revisit the change later, it's helpful to know exactly _why_ the change was made. Here's an example of the single commit message I'm looking for:

```
`FileSystemList.Get()` works properly on Fedora

The sigar package expects the existence of `/etc/mtab`; however, on some
distributions such as Fedora this file does not exist, and attempting to retrieve
the filesystem usage results in a "ENOFILE file does not exist". This commit 
addresses that shortcoming by falling back to using `/proc/mounts/`
```

There is no shortage of [posts](https://cbea.ms/git-commit/) describing how to write a good commit message. If you're looking for examples, the Linux kernel has tons of [good commit messages](https://github.com/torvalds/linux/commits/master).

Rest assured that I wouldn't ask of you what I'd expect from myself.

2022-10-06 03:13 UTC, cunnie commented
Hey @digiserg, Thanks for sticking with this. Some more notes:

- I like the change in title. In the third line of the commit message, please **describe _which_ containers don't have `/etc/mtab`**; I checked ubuntu, fedora, alpine, and golang Docker images, and they all have `/etc/mtab`, so I'm dying to know which containers don't include `/etc/mtab`. An example commit message:
```
/etc/mtab may not exist on containers, use /proc/mounts if not found

`/etc/mtab` doesn't exist on ubuntu:xenial Docker image.
```
- **Don't include the two merge commits in the PR** — they're not necessary, and they pollute the git history. If it was me, I'd probably do the following to get rid of them:

```shell
git switch ProcMounts
git reset origin/master --hard
git cherry-pick 80c60dc91a2888e7db6126a35192f992249cac8d
 # I'd run unit tests & make sure everything looked good before doing a force-push
```

2022-10-07 16:09 UTC, merged

2022-10-07 16:10 UTC, cunnie commented
Hey @digiserg : nice job on the commit message! Thank you.

2022-10-07 16:39 UTC, cunnie reviewed
Nice job, thanks.